-- MySQL Script generated by MySQL Workbench
-- Wed Jun  9 13:37:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd2409
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd2409
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd2409` DEFAULT CHARACTER SET utf8 ;
USE `bd2409` ;

-- -----------------------------------------------------
-- Table `bd2409`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`estado` (
  `idestado` INT NOT NULL,
  `estado` VARCHAR(150) NOT NULL,
  `codigoiso` VARCHAR(6) NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC) VISIBLE,
  UNIQUE INDEX `codigoiso_UNIQUE` (`codigoiso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2409`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`Pais` (
  `idPais` INT NOT NULL,
  `pais` VARCHAR(150) NOT NULL,
  `codigoiso` VARCHAR(6) NULL,
  PRIMARY KEY (`idPais`),
  UNIQUE INDEX `pais_UNIQUE` (`pais` ASC) VISIBLE,
  UNIQUE INDEX `codigoiso_UNIQUE` (`codigoiso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2409`.`escritor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`escritor` (
  `idEscritor` INT NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(12) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apPaterno` VARCHAR(50) NOT NULL,
  `apMaterno` VARCHAR(50) NULL,
  `fecha` DATETIME NULL COMMENT 'Fecha de nacimiento',
  `nacionalidad` VARCHAR(30) NULL,
  `idEstado` INT NOT NULL,
  `idPais` INT NOT NULL,
  PRIMARY KEY (`idEscritor`),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) VISIBLE,
  INDEX `fk_escritor_estado1_idx` (`idEstado` ASC) VISIBLE,
  INDEX `fk_escritor_Pais1_idx` (`idPais` ASC) VISIBLE,
  CONSTRAINT `fk_escritor_estado1`
    FOREIGN KEY (`idEstado`)
    REFERENCES `bd2409`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escritor_Pais1`
    FOREIGN KEY (`idPais`)
    REFERENCES `bd2409`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2409`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(150) NOT NULL,
  `anio` INT NULL,
  `isbn` VARCHAR(14) NULL,
  PRIMARY KEY (`idLibro`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2409`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`editorial` (
  `idEditorial` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idEditorial`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_editorial_Pais1_idx` (`Pais_idPais` ASC) VISIBLE,
  CONSTRAINT `fk_editorial_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `bd2409`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd2409`.`escribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd2409`.`escribe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `escritor_idEscritor` INT NOT NULL,
  `libro_idLibro` INT NOT NULL,
  `editorial_idEditorial` INT NOT NULL,
  INDEX `fk_libro_has_escritor_escritor1_idx` (`escritor_idEscritor` ASC) VISIBLE,
  INDEX `fk_libro_has_escritor_libro1_idx` (`libro_idLibro` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_escribe_editorial1_idx` (`editorial_idEditorial` ASC) VISIBLE,
  CONSTRAINT `fk_libro_has_escritor_libro1`
    FOREIGN KEY (`libro_idLibro`)
    REFERENCES `bd2409`.`libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_has_escritor_escritor1`
    FOREIGN KEY (`escritor_idEscritor`)
    REFERENCES `bd2409`.`escritor` (`idEscritor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escribe_editorial1`
    FOREIGN KEY (`editorial_idEditorial`)
    REFERENCES `bd2409`.`editorial` (`idEditorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
